Update build.yaml

diff --git a/.github/workflows/build.yaml b/.github/workflows/build.yaml
--- a/.github/workflows/build.yaml
+++ b/.github/workflows/build.yaml
@@ -59,13 +59,12 @@ jobs:
     outputs:
       version: ${{ steps.selected-version.outputs.version }}
 
-  build-ubuntu:
-    name: Ubuntu Build Matrix
+  build-ubuntu-x86:
+    name: Ubuntu x86_64 Build Matrix
     needs: get-version
     strategy:
       matrix:
         version: [18.04, 20.04, 22.04, 24.04]
-        arch: [x86_64, arm64]
     runs-on: ubuntu-${{ matrix.version }}
     steps:
       - uses: actions/checkout@v4
@@ -78,26 +77,17 @@ jobs:
         run: |
           sudo apt-get update -y
           sudo apt-get install -y build-essential g++ libsodium-dev gcc libtool autotools-dev automake pkg-config python3 bsdmainutils cmake libminiupnpc-dev libnatpmp-dev libzmq3-dev qtbase5-dev libqt5svg5-dev libdb-dev libdb++-dev
-          if [[ "${{ matrix.arch }}" == "arm64" ]]; then
-            sudo apt-get install -y g++-aarch64-linux-gnu
-          fi
 
       - name: Build depends
         run: |
           export FALLBACK_DOWNLOAD_PATH=https://explorer.yerbas.org/depends/
-          HOST=${{ matrix.arch }}-pc-linux-gnu
-          if [[ "${{ matrix.arch }}" == "arm64" ]]; then
-            HOST=aarch64-linux-gnu
-          fi
+          HOST=x86_64-pc-linux-gnu
           make -C depends -j$(nproc) HOST=$HOST BLS_VERSION=${BLS_VERSION}
 
       - name: Configure VKAX
         run: |
           ./autogen.sh
-          HOST=${{ matrix.arch }}-pc-linux-gnu
-          if [[ "${{ matrix.arch }}" == "arm64" ]]; then
-            HOST=aarch64-linux-gnu
-          fi
+          HOST=x86_64-pc-linux-gnu
           ./configure --prefix=$(pwd)/depends/$HOST \
                       --with-boost=$(pwd)/depends/boost \
                       --with-incompatible-bdb \
@@ -131,24 +121,102 @@ jobs:
           for DIR in $BUILD_DIR ${BUILD_DIR}_not_strip ${BUILD_DIR}_debug; do
             cd $DIR
             sha256sum * > checksums.txt
-            tar -czf ../$COMPRESS_DIR/$(basename $DIR)-${{ matrix.version }}-${{ matrix.arch }}-${{ needs.get-version.outputs.version }}.tar.gz *
+            tar -czf ../$COMPRESS_DIR/$(basename $DIR)-${{ matrix.version }}-x86_64-${{ needs.get-version.outputs.version }}.tar.gz *
             cd ..
           done
 
       - name: Upload Artifacts
         uses: actions/upload-artifact@v4
         with:
-          name: vkax-ubuntu-${{ matrix.version }}-${{ matrix.arch }}-${{ needs.get-version.outputs.version }}
+          name: vkax-ubuntu-${{ matrix.version }}-x86_64-${{ needs.get-version.outputs.version }}
           path: $COMPRESS_DIR
 
       - name: Upload Test Binaries
         uses: actions/upload-artifact@v4
         with:
-          name: vkax-ubuntu-${{ matrix.version }}-${{ matrix.arch }}-test-${{ needs.get-version.outputs.version }}
+          name: vkax-ubuntu-${{ matrix.version }}-x86_64-test-${{ needs.get-version.outputs.version }}
+          path: $TEST_DIR
+
+  build-ubuntu-arm:
+    name: Ubuntu ARM64 Build Matrix
+    needs: get-version
+    strategy:
+      matrix:
+        version: [18.04, 20.04, 22.04, 24.04]
+    runs-on: ubuntu-${{ matrix.version }}
+    steps:
+      - uses: actions/checkout@v4
+      - uses: actions/download-artifact@v4
+        with:
+          name: version
+          path: .
+
+      - name: Install Dependencies
+        run: |
+          sudo apt-get update -y
+          sudo apt-get install -y build-essential g++ libsodium-dev gcc libtool autotools-dev automake pkg-config python3 bsdmainutils cmake libminiupnpc-dev libnatpmp-dev libzmq3-dev qtbase5-dev libqt5svg5-dev libdb-dev libdb++-dev g++-aarch64-linux-gnu
+
+      - name: Build depends
+        run: |
+          export FALLBACK_DOWNLOAD_PATH=https://explorer.yerbas.org/depends/
+          HOST=aarch64-linux-gnu
+          make -C depends -j$(nproc) HOST=$HOST BLS_VERSION=${BLS_VERSION}
+
+      - name: Configure VKAX
+        run: |
+          ./autogen.sh
+          HOST=aarch64-linux-gnu
+          ./configure --prefix=$(pwd)/depends/$HOST \
+                      --with-boost=$(pwd)/depends/boost \
+                      --with-incompatible-bdb \
+                      --enable-upnp-default \
+                      --with-zmq \
+                      --with-gui=qt5
+
+      - name: Build Binary
+        run: |
+          make -j$(nproc)
+          mkdir -p $BUILD_DIR ${BUILD_DIR}_not_strip $TEST_DIR
+          mv src/{vkax-cli,vkaxd,qt/vkax-qt} $BUILD_DIR/
+          cp src/{vkax-cli,vkaxd,qt/vkax-qt} $TEST_DIR/
+          mv src/{vkax-cli,vkaxd,qt/vkax-qt} ${BUILD_DIR}_not_strip/
+          strip $BUILD_DIR/* || echo "strip failed — skipping"
+
+      - name: Build Debug Binary
+        run: |
+          make clean
+          make distclean
+          ./autogen.sh
+          ./configure --prefix=$(pwd)/depends/$HOST --disable-tests --enable-debug \
+                      --with-incompatible-bdb --enable-upnp-default --with-zmq --with-gui=qt5
+          make -j$(nproc)
+          mkdir -p ${BUILD_DIR}_debug
+          mv src/{vkax-cli,vkaxd,qt/vkax-qt} ${BUILD_DIR}_debug/
+
+      - name: Generate Checksum and Compress
+        run: |
+          mkdir -p $COMPRESS_DIR
+          for DIR in $BUILD_DIR ${BUILD_DIR}_not_strip ${BUILD_DIR}_debug; do
+            cd $DIR
+            sha256sum * > checksums.txt
+            tar -czf ../$COMPRESS_DIR/$(basename $DIR)-${{ matrix.version }}-arm64-${{ needs.get-version.outputs.version }}.tar.gz *
+            cd ..
+          done
+
+      - name: Upload Artifacts
+        uses: actions/upload-artifact@v4
+        with:
+          name: vkax-ubuntu-${{ matrix.version }}-arm64-${{ needs.get-version.outputs.version }}
+          path: $COMPRESS_DIR
+
+      - name: Upload Test Binaries
+        uses: actions/upload-artifact@v4
+        with:
+          name: vkax-ubuntu-${{ matrix.version }}-arm64-test-${{ needs.get-version.outputs.version }}
           path: $TEST_DIR
 
   build-macos:
-    name: macOS Build
+    name: macOS x86_64 Build
     needs: get-version
     strategy:
       matrix:
@@ -227,7 +295,7 @@ jobs:
           path: macos-dmg
 
   build-macos-arm64:
-    name: macOS Build
+    name: macOS ARM64 Build
     needs: get-version
     strategy:
       matrix:
